name: Golang CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set PATH for Go
        run: echo "PATH=$PATH:/usr/local/go/bin" >> $GITHUB_ENV

      - name: Build Go application
        run: |
          cd /var/www/crud_go
          git fetch --all
          git reset --hard origin/master
          go mod tidy
          go build -o crud_go
          echo "Build Success"

      - name: Enable linger for user session
        run: loginctl enable-linger $(whoami)

      - name: Check & Restart Service
        run: |
          export XDG_RUNTIME_DIR=/run/user/$(id -u)
          systemctl --user daemon-reload
          if systemctl --user is-active --quiet crud_go; then
            echo "Service is running, restarting..."
            systemctl --user restart crud_go
          echo "Service restarted successfully"
          else
            echo "Service is not running, starting..."
            systemctl --user start crud_go
            echo "Service started successfully"
          fi

      - name: Service Status
        run: |
          systemctl --user status crud_go --no-pager