name: Golang CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug PATH
        run: echo $PATH

      - name: Build Go application
        run: |
          whoami
          cd /var/www/crud_go
          go mod tidy
          go build -o crud_go

      - name: Check & Restart Service
        run: |
          if systemctl is-active --quiet myapp; then
            echo "Service is running, restarting..."
            sudo systemctl restart myapp
          else
            echo "Service is not running, starting..."
            sudo systemctl start myapp
          fi

      - name: Check Service Status
        run: sudo systemctl status myapp --no-pager
